### ISSUE TITLE
Legendary failing to download. Requires a baseurl now?

### ISSUE THREAD

**Issue by comradesean** [solderq35/hitman-3-downpatch#2]
Legendary is erroring out with the following

`Traceback (most recent call last):
File "legendary\cli.py", line 3137, in <module>
File "legendary\cli.py", line 3054, in main
File "legendary\cli.py", line 948, in install_game
File "legendary\core.py", line 1438, in prepare_download
ValueError: No base URLs found, please try again.`

I'm testing the waters with the --base-url flag, but can't seem to get anywhere. I've tried both https://download.epicgames.com and https://epicgames-download1.akamaized.net

`legendary install Eider --manifest Eider_Windows_5259620.manifest --base-url https://download.epicgames.com`

**Comment by comradesean** [comment]
Alright, so the way to fix it is to first run install without the --manifest flag and once that finishes you can run it with the manifest. Forget the --base-url flag.
